#!/usr/bin/env python
import binascii


def xor(s1, s2):
	return ''.join(chr(ord(a)^ord(b)) for a, b in zip(s1, s2))


def main():
	xored = xor('test', '1234')
	print('ASCII: \t %s' % xored)
	print('\nNumeric: \t %s' % ored.encode('hex'))


if __name__ == '__main__':
	main()
