#!/usr/bin/env python
import urllib, urllib2


SITE = 'http://'
DATA = {
	'a': 'b',
	'b': 'c'
}


def main():
	cookie_handler   = urllib2.HTTPCookieProcessor()
	redirect_handler = urllib2.HTTPRedirectHandler()
	opener = urllib2.build_opener(redirect_handler, cookie_handler)

	data = urllib.urlencode(DATA)
	request = urllib2.Request(SITE)
	content = opener.open(request, data).read()

	print(content)


if __name__ == '__main__':
	main()
