#!/usr/bin/env python
import re
from urllib2 import urlopen
from urllib import urlencode


SITE = 'http://'
DATA = {
	'a': 'b',
	'b': 'c'
}


def main():
	content = urlopen(SITE).read()

	# do sth. with content
	# match = re.search('', content)

	data = urlencode(DATA)
	content = urlopen(SITE, data).read()

	print(content)


if __name__ == '__main__':
	main()
