#!/usr/bin/env python
import socket
 

ADDR = ('localhost', 7777)
MESSAGE = 'asdf'


def main():
	s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
	s.sendto(MESSAGE, ADDR)
	msg, addr = s.recvfrom(1024)
	print(msg)


if __name__ == '__main__':
	main()
